#!/bin/bash
docker build --build-arg pg_version="9.4" -t postgresql_tools:9.4 .
docker build --build-arg pg_version="9.5" -t postgresql_tools:9.5 .
docker build --build-arg pg_version="9.6" -t postgresql_tools:9.6 .
docker build --build-arg pg_version="10" -t postgresql_tools:10 .
docker build --build-arg pg_version="11" -t postgresql_tools:11 .
docker build --build-arg pg_version="12" -t postgresql_tools:12 .
